### ISSUE TITLE
Error in installing

### ISSUE THREAD

**Issue by dtrocellier** [ajuelosemmanuel/philINT#2]
I tried to install the library with pip in my conda env and in a new conda env and I have the following issue wich is not that clear. 
 
pip install philINT
ERROR: Could not find a version that satisfies the requirement philINT (from versions: none)
ERROR: No matching distribution found for philINT

**Comment by ajuelosemmanuel** [comment]
Hi !
Which Python version do you use ?

**Comment by dtrocellier** [comment]
Python 3.10 and 3.9

**Comment by ajuelosemmanuel** [comment]
I think my PyPI project didn't upload for some reason - I'm working on this right now

Edit :  I absolutely forgot to make a release... So the package never got uploaded !

**Comment by ajuelosemmanuel** [comment]
After more investigation, I have an issue when publishing the package - I'm trying my best to solve the issue asap !

**Comment by ajuelosemmanuel** [comment]
Should be good now - waiting for your confirmation to close the issue.

The project appears now here : https://pypi.org/project/philINT/
